env:
  arjuna_options:
    app.url: "http://env"

  user_options:
    eoption: 1

env1:
  arjuna_options:
    app.url: "https://env1"

  user_options:
    user: "env1_user" 
    pwd: "env1_pwd"


env2:
  arjuna_options:
    app.url: "https://env2"

  user_options:
    user: "env2_user" 
    pwd: "env2_pwd"

chrome:
  arjuna_options:
    browser.name: chrome

  user_options:
    test.url: ta.world

firefox:
  arjuna_options:
    browser.name: firefox

  user_options:
    test.url: rahul.world

jelson:
  arjuna_options:
    browser.name: firefox

  user_options:
    test.url: jelson.world
