gp1:
  conf: data1_env1
  imod:
    - check_gp1

gp2:
  conf: data2_env2
  imod:
    - check_gp2

gp3:
  conf: data1_env1
  imod:
    - check_group_info_1

gp4:
  conf: data2_env2
  imod:
    - check_group_info_2

gp_tag:

  irule:
    - "with tags slow"

gp_rules:

  conf: data2_env2

  irule:
    - "package *= data"

  erule:
    - "module !*= excel"

check_conf:
  conf: firefox

  imod:
    - check_group_conf
    - check_01_simple_test

all_gp1:
  conf: chrome

  irule:
    - "package *= pkg"

all_gp2:
  conf: firefox

  irule:
    - "package *= pkg"


    